- name: Report a powershell script
  hosts: all
  vars:
    ps_script: "{{ ps_script }}"
  gather_facts: true
  tasks:
  - name: Remove old file, if present
    win_file:
      path: C:\test-script.ps1
      state: absent
      
  - name: Create powershell script in remote machine
    win_lineinfile:
      path: C:\test-script.ps1
      state: present
      create: yes
      line: |
        {{ ps_script }}

  - name: Execute a comand in the remote shell
    win_shell: C:\test-script.ps1
    register: script_output
  
  - name: set fact content
    set_fact:
      script_result: "{{ script_output.stdout_lines }} "

  - name: write content
    debug: var=script_output
 
  - name: get date
    set_fact:
      date="{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"

  - name: create HTML report
    template:
      src: report-powershell.j2
      dest: /tmp/report-powershell-{{ date }}.html
    delegate_to: tower-01
    run_once: true