- name: Add All Server to a Group
  hosts: all
  gather_facts: true
  vars:
    group_id: "{{ group_id }}"
    keyword: "{{ keyword }}"                #2019
  tasks:
  - name: Set fact inventory_hostname
    set_fact:
      hostname: "{{ inventory_hostname }}"

#  - debug: var=ansible_facts['system']

  - name: Add servers to the specified group
    uri:
      url: "https://localhost/api/v2/groups/{{ group_id }}/hosts/"
      method: post
      body_format: json
      body: >
        {
          "name": "{{ hostname }}",
          "description": "",
          "enabled": true,
          "instance_id": "",
          "variables": ""
        }
      user: admin
      password: redhat
      validate_certs: no
      force_basic_auth: yes
      status_code: 204
    register: result_post
#    when: keyword in "{{ ansible_facts['system'] }}"
    delegate_to: ksansiblepoct2.simcacls.local

 # - debug: var=result_post