- name: Test windows connection
  hosts: all
  gather_facts: true
  tasks:
  - name: Test win_ping 
    win_ping:

  - debug: var=ansible_facts.hostname
  
  - name: set stats
    set_stats:
      data: 
        first_data: "{{ ansible_facts.hostname }}"

        